PyTorchKorea/hub-kr

pytorch_vision_deeplabv3_resnet101.md

_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
_이슈 또는 PR 번호 앞에 #을 붙이시면 제목을 바로 확인하실 수 있습니다. (예. #999 )_  
- **이슈 번호**: #10 
_이 PR로 무엇이 달라지는지 대략적으로 알려주세요._  
deeplabv3_resnet101 문서를 번역했습니다!

Translate deeplabv3_resnet101.md

---

pytorch_vision_densenet.md

_더 자세한 내용은 [기여하기 문서](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/CONTRIBUTING.md)를 참고해주세요._<br />
- **이슈 번호**: #9 
pytorch_vision_densenet.md 번역

Translate vision_densenet

---

CONTRIBUTING.md

- **이슈 번호**: #(숫자)
#20   
`CONTRIBUTING.md`의 초안을 추가하였습니다.

CONTRIBUTING.md 문서 추가

---

pytorch_vision_squeezenet.md

Signed-off-by: Jihoon Lee <zhoonit@gmail.com>
- **이슈 번호**: #(숫자)
squeezenet 번역을 추가하였습니다.

[번역] vision_squeezenet 모델

---

nicolalandro_ntsnet-cub200_ntsnet.md

[번역] NTSNET 모델

---

pytorch_vision_meal_v2.md

Translate pytorch_vision_meal_v2

---

CONTRIBUTING.md

[Edit]:CONTRIBUTION.md

---

hustvl_yolop.md

- **이슈 번호**: #37 
YOLOP 모델에 대한 번역

[번역] YOLOP

---

pytorch_fairseq_roberta.md

- **이슈 번호**: #56 
RoBERTa 번역 추가

Translate pytorch_fairseq_roberta.md

---

facebookresearch_pytorch-gan-zoo_dcgan.md

- **이슈 번호**: #64 
facebookresearch_pytorch-gan-zoo_dcgan.md 번역본 입니다.

DCGAN ON FASHIONGEN 번역

---

facebookresearch_WSL-Images_resnext.md

- **이슈 번호**: #88 
ResNeXt WSL 모델 번역

Translate ResNeXtWSL

---

pytorch_fairseq_translation.md

- **이슈 번호**: #68 
TROMSFORMER(NMT)문서 번역

TRANSFORMER(NMT) 번역

---

pytorch_vision_alexnet.md

- **이슈 번호**: #46 
AlexNet 영한 번역

번역: AlexNet 번역

---

pytorch_vision_meal_v2.md

- **이슈 번호**: #49
링크가 제대로 걸려있지 않아 수정하였습니다.

fix: meal_v2 typo error

---

pytorch_vision_fcn_resnet101.md

- **이슈 번호**: #54 
본래 페이지에 `tag`된 단어들이 번역하면서 사라져서 이를 수정하였고,
"[여기] 에서 볼수있습니다. (링크)" 와 같이 링크가 제대로 걸려있지 않아 수정합니다.

fix: fcn docs typo err

---

pytorch_vision_ghostnet.md

- **이슈 번호**: #39 
pytorch_vision_ghostnet 번역

pytorch_vision_ghostnet 번역(#39)

---

facebookresearch_pytorch-gan-zoo_pgan.md

facebookresearch_pytorch_gan-zoo-pgan 번역

---

pytorch_vision_inception_v3.md

pytorch_vision_inception_v3.md 번역본입니다.
- **이슈 번호**: #69 
pytorch_vision_inception_v3.md 번역본입니다.

pytorch_vision_inception_v3 번역

---

pytorch_vision_googlenet.md

pytorch_vision_googlenet 번역본입니다.
- **이슈 번호**: #76 
GoogLeNet 문서 번역본 입니다.

pytorch_vision_googlenet 번역

---

facebookresearch_semi-supervised-ImageNet1K-models_resnext.md

- **이슈 번호**: #61 
SEMI-SUPERVISED AND SEMI-WEAKLY SUPERVISED IMAGENET MODELS 번역

SEMI-SUPERVISED AND SEMI-WEAKLY SUPERVISED IMAGENET MODELS 번역

---

facebookresearch_semi-supervised-ImageNet1K-models_resnext.md

- **이슈 번호**: https://github.com/PyTorchKorea/hub-kr/issues/117
backslash bugfix

remove quotes for compiling

---

facebookresearch_pytorchvideo_slowfast.md

- **이슈 번호**: #45 
SlowFast 모델에 대한 번역을 진행하였습니다.

SlowFast 번역

---

nvidia_deeplearningexamples_resnet50.md

ResNet50 번역

---

nvidia_deeplearningexamples_resnext.md

- **이슈 번호**: #98 
ResNeXt101 모델 번역

ResNeXt101 번역

---

facebookresearch_pytorchvideo_resnet.md

- **이슈 번호**: #62 
3D ResNet 번역

3D ResNet 번역

---

nvidia_deeplearningexamples_tacotron2.md

- **이슈 번호**: #99 
tacotron2 모델 번역

tacotron2 번역

---

pytorch_vision_resnest.md

ResNeSt 번역

---

pytorch_vision_wide_resnet.md

Wide ResNet 번역
